[package]
name = "dsbuild2"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.39.3", features = ["sync"] }
futures = "0.3.30"
thiserror = "1.0.63"
rand = { version = "0.8.5", features = ["std_rng"] }

[dev-dependencies]
test-case = "*"
